(()=>{'use strict';
const {RouletteEngine,POCKETS,name,cls}=window.RT,$=id=>document.getElementById(id),KEY='ejr-american-roulette-tracker-v1',VER='1.10.0',MISS13=26/38;
const ok=v=>/^(00|0|[1-9]|[12][0-9]|3[0-6])$/.test(String(v)),fmt=x=>`${x>=0?'+':''}${x.toFixed(2)}`;
let outcomes=[];try{outcomes=(JSON.parse(localStorage.getItem(KEY)||'[]')||[]).map(String).filter(ok)}catch{}
let engine=new RouletteEngine(outcomes),E={z:$('zero'),b:$('board'),st:$('status'),s50:$('s50'),s13:$('s13'),sn:$('sn'),h:$('hist'),w:$('why'),q:$('q')};
const save=()=>localStorage.setItem(KEY,JSON.stringify(outcomes));
function gap(p){for(let i=outcomes.length-1,g=0;i>=0;i--,g++)if(outcomes[i]===p)return g;return outcomes.length}
function mk(v){const b=document.createElement('button');b.className='num '+cls(v);b.dataset.p=v;b.innerHTML=`<span>${v}</span><span class="cnt"></span><span class="gap"></span>`;b.onclick=()=>add(v);return b}
['0','00'].forEach(v=>E.z.appendChild(mk(v)));for(let i=1;i<=36;i++)E.b.appendChild(mk(String(i)));
function rebuild(){engine=new RouletteEngine(outcomes)}
function add(v){v=String(v).trim();if(!ok(v))return;outcomes.push(v);engine.update(v);save();render();E.q.value=''}
function addBadge(b,text,klass='badge'){const z=document.createElement('span');z.className=klass;z.textContent=text;b.appendChild(z)}
function render(){const m=engine.model(),ct=Object.fromEntries(POCKETS.map(p=>[p,0]));outcomes.forEach(v=>ct[v]++);E.st.innerHTML=`<b>${outcomes.length}</b> spins · last <b>${engine.last||'—'}</b> · <b>${POCKETS.filter(p=>ct[p]).length}/38</b> seen`;const byP=new Map(m.ranked.map(x=>[x.p,x]));
 POCKETS.forEach(p=>{const b=document.querySelector(`[data-p="${p}"]`),x=byP.get(p);b.classList.remove('opp1','opp2','opp3','last');b.querySelectorAll('.rank').forEach(n=>n.remove());b.querySelector('.cnt').textContent=ct[p]||'';b.querySelector('.gap').textContent=outcomes.length?'g '+gap(p):'';if(p===engine.last)b.classList.add('last');if(x&&x.rank){b.classList.add('opp'+(4-x.rank));addBadge(b,'★'+x.rank,'rank');b.title=`score ${x.score.toFixed(2)} | 50 ${x.primary.toFixed(2)} | relation ${x.cross13.toFixed(2)} | cold ${x.coldDirect.toFixed(2)} | helper ${x.coldTo50.toFixed(2)} | history ${x.history.toFixed(2)}`}});
 document.querySelectorAll('.bet').forEach(b=>{b.classList.remove('signal','watch','cold1','cold2','cold3');b.querySelectorAll('.badge').forEach(x=>x.remove());const f=b.dataset.f,n=b.dataset.n,meta=b.querySelector('.meta'),hn=m.hist.net.get(n)||0;if(['K','P','R'].includes(f)){const s=m.ss.find(x=>x.f===f),helper=m.rel50.get(n)||0;if(s.a&&s.a.t===n){b.classList.add('signal');addBadge(b,'BET');meta.textContent=`6+ from ${name(s.a.src)} · open ${s.a.age+1}${Math.abs(helper)>.05?` · h ${fmt(helper)}`:''}${Math.abs(hn)>.12?` · hist ${fmt(hn)}`:''}`}else if(s.watch&&s.watch.t===n){b.classList.add('watch');addBadge(b,'WATCH');meta.textContent=`5 ${name(s.watch.src)} · wait 1 more`}else if(s.a&&s.a.src===n)meta.textContent='unresolved source';else if(s.rs===n&&s.rl>1)meta.textContent=`streak ${s.rl}${s.rl===5?' · WATCH':''}`;else meta.textContent=`${Math.abs(helper)>.05?`helper ${fmt(helper)}`:''}${Math.abs(hn)>.12?`${Math.abs(helper)>.05?' · ':''}hist ${fmt(hn)}`:''}`}else{const c=m.cc.find(x=>x.f===f&&x.n===n),rel=m.rel13.get(n)||0,tail=Math.pow(MISS13,c.g);if(c.on){b.classList.add(c.strong?(c.g>=10?'cold3':'cold2'):'cold1');addBadge(b,c.strong?'STRONG':'HELP','badge coldbadge')}meta.textContent=`${c.g?`cold ${c.g} · ${(100*tail).toFixed(tail<.1?1:0)}%`:''}${c.on&&!c.strong?' · weak helper':''}${c.strong?' · strong helper':''}${Math.abs(rel)>.05?` · rel ${fmt(rel)}`:''}${Math.abs(hn)>.12?` · hist ${fmt(hn)}`:''}`||'hit now'}});
 const bet=m.as.map(x=>`${name(x.a.t)} ← ${name(x.a.src)}`),watch=m.ws.map(x=>`${name(x.watch.t)} WATCH`);E.s50.textContent=[...bet,...watch].join(' · ')||'No 5+ streak';E.s50.classList.toggle('muted',!(bet.length||watch.length));const strong=m.strongCold.slice().sort((a,b)=>b.w-a.w).map(x=>`${x.s} c${x.g}`),weak=m.ac.filter(x=>!x.strong).map(x=>`${x.s} c${x.g} helper`);E.s13.textContent=[...strong,...weak].slice(0,5).join(' · ')||'No cold 5+ dozen/column';E.s13.classList.toggle('muted',!(strong.length||weak.length));const picks=m.ranked.filter(x=>x.rank).sort((a,b)=>a.rank-b.rank);E.sn.textContent=picks.length?picks.map(x=>`★${x.rank} ${x.p}`).join(' · '):'Waiting for 6+ 50/50 or cold 7+';E.sn.classList.toggle('muted',!picks.length);
 E.h.innerHTML='';outcomes.slice(-80).reverse().forEach(v=>{const d=document.createElement('div');d.className='chip '+cls(v);d.textContent=v;E.h.appendChild(d)});if(!outcomes.length)E.h.innerHTML='<span class="muted" style="font-size:.55rem">No spins yet.</span>';
 E.w.innerHTML='';if(picks.length)picks.forEach(x=>{const d=document.createElement('div');d.className='w';d.innerHTML=`<b>★${x.rank} ${x.p} · ${x.score.toFixed(2)}</b><p>50 ${x.primary.toFixed(2)} · rel ${x.cross13.toFixed(2)} · cold ${x.coldDirect.toFixed(2)} · helper ${x.coldTo50.toFixed(2)} · hist ${x.history>=0?'+':''}${x.history.toFixed(2)}</p>`;E.w.appendChild(d)});else E.w.innerHTML='<div class="w"><b>Waiting for stronger current pressure</b><p>5-streak = WATCH. 6+ = BET. Cold 5–6 helps scoring; cold 7+ can activate number picks.</p></div>'}
$('add').onclick=()=>add(E.q.value);E.q.onkeydown=e=>{if(e.key==='Enter')add(E.q.value)};$('undo').onclick=()=>{if(outcomes.length){outcomes.pop();rebuild();save();render()}};$('clear').onclick=()=>{if(confirm('Clear all logged spins?')){outcomes=[];rebuild();save();render()}};$('export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({app:'American Roulette Tracker',version:VER,outcomes},null,2)],{type:'application/json'}));a.download='roulette-session.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};$('import').onclick=()=>{const s=prompt('Paste JSON or roulette values:');if(!s)return;let a;try{const j=JSON.parse(s);a=Array.isArray(j)?j:j.outcomes}catch{a=s.split(/[\s,;|]+/)}if(Array.isArray(a)){const v=a.map(String).filter(ok);if(v.length){outcomes=v;rebuild();save();render()}}};render();
})();