(()=>{'use strict';
const {RouletteEngine,POCKETS,BETS,name,cls,ranked50,ranked13,clamp}=window.RT,$=id=>document.getElementById(id);
function makeNum(p){const b=document.createElement('button');b.className='num '+cls(p);b.dataset.p=p;b.textContent=p;return b}
for(const p of ['0','00'])$('zero').appendChild(makeNum(p));for(let i=1;i<=36;i++)$('board').appendChild(makeNum(String(i)));
for(const [labels,klass] of [[['D1','D2','D3'],'r3'],[['C1','C2','C3'],'r3'],[['L','E','R','B','O','H'],'r6']]){const row=document.createElement('div');row.className=klass;for(const n of labels){const b=document.createElement('button');b.className='bet';b.dataset.n=n;b.innerHTML=`${name(n)}<span class="meta"></span>`;row.appendChild(b)}$('bets').appendChild(row)}
class RandomWheel{constructor(){this.a=new Uint32Array(2048);this.i=this.a.length;this.secure=!!(globalThis.crypto&&typeof globalThis.crypto.getRandomValues==='function')}next(){if(!this.secure)return POCKETS[Math.floor(Math.random()*38)];for(;;){if(this.i>=this.a.length){globalThis.crypto.getRandomValues(this.a);this.i=0}const x=this.a[this.i++],lim=Math.floor(4294967296/38)*38;if(x<lim)return POCKETS[x%38]}}}
const fnum=x=>Number.isInteger(x)?String(x):x.toFixed(2).replace(/0+$/,'').replace(/\.$/,''),money=x=>Math.round(x*1e6)/1e6;
function cfg(){const amt=id=>clamp(Number($(id).value)||0,0,1e9),cnt=(id,max)=>clamp(Math.floor(Number($(id).value)||1),1,max);return{useNum:$('useNum').checked,amtNum:amt('amtNum'),cntNum:cnt('cntNum',3),use50:$('use50').checked,amt50:amt('amt50'),cnt50:cnt('cnt50',3),use13:$('use13').checked,amt13:amt('amt13'),cnt13:cnt('cnt13',6)}}
function settle(label,v,pay){return BETS.get(label).has(v)?pay:-1}
function draw(points){const c=$('chart'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#53636d';ctx.beginPath();ctx.moveTo(0,h/2);ctx.lineTo(w,h/2);ctx.stroke();if(points.length<2)return;let lo=Math.min(0,...points),hi=Math.max(0,...points);if(hi===lo){hi++;lo--}ctx.strokeStyle='#d9e2e7';ctx.lineWidth=2;ctx.beginPath();points.forEach((v,i)=>{const x=i/(points.length-1)*w,y=h-((v-lo)/(hi-lo))*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function renderFinal(engine){const m=engine.model(),byP=new Map(m.ranked.map(x=>[x.p,x]));document.querySelectorAll('.num').forEach(b=>{b.classList.remove('pick');b.querySelectorAll('.rank').forEach(x=>x.remove());const x=byP.get(b.dataset.p);if(x&&x.rank){b.classList.add('pick');const z=document.createElement('span');z.className='rank';z.textContent='★'+x.rank;b.appendChild(z)}});document.querySelectorAll('.bet').forEach(b=>{b.classList.remove('signal','cold');const n=b.dataset.n,meta=b.querySelector('.meta'),s=m.as.find(x=>x.a.t===n),c=m.ac.find(x=>x.n===n);if(s){b.classList.add('signal');meta.textContent='BET'}else if(c){b.classList.add('cold');meta.textContent='cold '+c.g}else meta.textContent=''});const picks=m.ranked.filter(x=>x.rank).sort((a,b)=>a.rank-b.rank),r50=ranked50(m),r13=ranked13(m);$('finalWhy').innerHTML=`<b>50/50:</b> ${r50.length?r50.map((x,i)=>`#${i+1} ${name(x.n)}`).join(' · '):'none'}<br><b>1/3:</b> ${r13.length?r13.map((x,i)=>`#${i+1} ${name(x.n)} c${x.g}`).join(' · '):'none'}<br><b>Numbers:</b> ${picks.length?picks.map(x=>`★${x.rank} ${x.p}`).join(' · '):'none'}`}
function resizeChart(){const c=$('chart'),r=c.getBoundingClientRect(),d=Math.max(1,window.devicePixelRatio||1);c.width=Math.max(100,Math.round(r.width*d));c.height=Math.max(60,Math.round(r.height*d))}
async function run(){let games=clamp(Math.floor(Number($('games').value)||0),1,1e6);$('games').value=games;const C=cfg(),engine=new RouletteEngine(),rng=new RandomWheel();$('run').disabled=true;$('bar').style.width='0%';let wager=0,net=0,betSpins=0,b50=0,w50=0,b13=0,w13=0,bn=0,wn=0,peak=0,maxDD=0;const curve=[0],log=[],sampleEvery=Math.max(1,Math.floor(games/800));
 for(let i=0;i<games;i++){const m=engine.model(),fifty=ranked50(m).slice(0,C.cnt50).map(x=>x.n),thirds=ranked13(m).slice(0,C.cnt13).map(x=>x.n),nums=m.ranked.filter(x=>x.rank&&x.rank<=C.cntNum).sort((a,b)=>a.rank-b.rank).map(x=>x.p),bF=C.use50&&C.amt50>0?fifty:[],bT=C.use13&&C.amt13>0?thirds:[],bN=C.useNum&&C.amtNum>0?nums:[],result=rng.next();let units=0,pl=0;
  if(bF.length||bT.length||bN.length){betSpins++;for(const n of bF){units+=C.amt50;b50++;const q=settle(n,result,1);pl+=q*C.amt50;if(q>0)w50++}for(const n of bT){units+=C.amt13;b13++;const q=settle(n,result,2);pl+=q*C.amt13;if(q>0)w13++}for(const p of bN){units+=C.amtNum;bn++;const q=p===result?35:-1;pl+=q*C.amtNum;if(q>0)wn++}units=money(units);pl=money(pl);wager=money(wager+units);net=money(net+pl);peak=Math.max(peak,net);maxDD=Math.max(maxDD,peak-net)}
  engine.update(result);if(i%sampleEvery===0||i===games-1)curve.push(net);log.push({i:i+1,bF,bT,bN,result,units,pl,net});if(log.length>100)log.shift();if((i+1)%4000===0){$('bar').style.width=((i+1)/games*100).toFixed(1)+'%';await new Promise(requestAnimationFrame)}}
 const roi=wager?100*net/wager:0,expected=-wager*(2/38);$('bar').style.width='100%';$('stSpins').textContent=games.toLocaleString();$('stBetSpins').textContent=`${betSpins.toLocaleString()} (${(100*betSpins/games).toFixed(1)}%)`;$('stWager').textContent=fnum(wager);$('stNet').textContent=(net>=0?'+':'')+fnum(net);$('stRoi').textContent=(roi>=0?'+':'')+roi.toFixed(2)+'%';$('stExpected').textContent=expected.toFixed(2);$('st50').textContent=`${w50} / ${b50}`;$('st13').textContent=`${w13} / ${b13}`;$('stNum').textContent=`${wn} / ${bn}`;$('summary').innerHTML=`<b>Setup:</b> numbers ${C.useNum?fnum(C.amtNum)+' × top '+C.cntNum:'OFF'}; 50/50 ${C.use50?fnum(C.amt50)+' × top '+C.cnt50:'OFF'}; 1/3 ${C.use13?fnum(C.amt13)+' × top '+C.cnt13:'OFF'}. <b>Net:</b> ${net>=0?'+':''}${fnum(net)} on ${fnum(wager)} wagered (${roi.toFixed(2)}%). <b>Max DD:</b> ${maxDD.toFixed(2)}.`;draw(curve);renderFinal(engine);$('logBody').innerHTML=log.reverse().map(r=>`<tr><td>${r.i}</td><td>${r.bF.length?r.bF.map(name).join(' + '):'—'}</td><td>${r.bT.length?r.bT.map(name).join(' + '):'—'}</td><td>${r.bN.length?r.bN.join(', '):'—'}</td><td><b>${r.result}</b></td><td>${r.units?fnum(r.units):'—'}</td><td>${r.units?(r.pl>=0?'+':'')+fnum(r.pl):'—'}</td><td>${r.net>=0?'+':''}${fnum(r.net)}</td></tr>`).join('');$('run').disabled=false}
function sync(id,card,controls){const on=$(id).checked;$(card).classList.toggle('off',!on);controls.forEach(x=>$(x).disabled=!on)}
[['useNum','cfgNum',['amtNum','cntNum']],['use50','cfg50',['amt50','cnt50']],['use13','cfg13',['amt13','cnt13']]].forEach(([id,card,c])=>{$(id).addEventListener('change',()=>sync(id,card,c));sync(id,card,c)});
$('run').onclick=async()=>{try{await run()}catch(e){console.error(e);$('run').disabled=false;$('summary').innerHTML='<b>Simulation error:</b> '+String(e&&e.message||e)}};window.addEventListener('resize',()=>{resizeChart();draw([0])});resizeChart();draw([0]);renderFinal(new RouletteEngine());
})();